apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    {{- include "anysource.frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.frontend.enabled }}
  replicas: {{ .Values.frontend.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "anysource.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "anysource.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.frontend.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.frontend.pullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "anysource.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          env:
            - name: PUBLIC_AUTH_CLIENT_ID
              value: {{ .Values.global.auth_client_id | quote }}
            - name: PUBLIC_APP_URL
              value: "https://{{ .Values.global.domain }}"
            - name: PUBLIC_BACKEND_URL
              value: "https://{{ .Values.global.domain }}"
            - name: PUBLIC_BACKEND_VERSION
              value: {{ .Values.image.backend.tag | quote }}
            - name: PUBLIC_WEBAPP_VERSION
              value: {{ .Values.image.frontend.tag | quote }}
            - name: PUBLIC_VERSION_URL
              value: {{ .Values.global.version_url | default "https://anysource-version.s3.amazonaws.com/version.json" | quote }}
            {{- if .Values.global.oauth_broker_url }}
            - name: PUBLIC_OAUTH_BROKER_URL
              value: {{ .Values.global.oauth_broker_url | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
