{{- if .Values.telemetry.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: telemetry-post-upgrade
  labels:
    {{- include "anysource.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "anysource.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: telemetry
    spec:
      restartPolicy: Never
      containers:
        - name: telemetry
          image: alpine:3.20
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "=== Telemetry Post-Upgrade Hook ==="
              echo "Starting at: $(date)"
              echo "Running as user: $(whoami) (UID: $(id -u))"
              echo ""
              echo "Installing dependencies..."
              apk add --no-cache bash curl jq coreutils openssl util-linux || true
              # Verify critical packages were installed (ignore APK ownership warnings)
              if command -v bash >/dev/null && command -v curl >/dev/null && command -v jq >/dev/null; then
                echo "✓ Dependencies installed successfully"
              else
                echo "✗ Failed to install critical dependencies"
                exit 1
              fi
              echo ""
              echo "Checking script..."
              if [ -f /scripts/capture-deployment-completion.sh ]; then
                echo "✓ Script found at /scripts/capture-deployment-completion.sh"
              else
                echo "✗ Script not found!"
                exit 1
              fi
              echo ""
              echo "Running deployment completion telemetry..."
              bash /scripts/capture-deployment-completion.sh \
                eks "{{ .Values.global.domain }}" "{{ .Values.global.deployment.infraVersion | default .Chart.Version }}" success
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SENTRY_DSN
            - name: AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AUTH_API_KEY
            - name: ENVIRONMENT
              value: "{{ .Values.global.environment | default "production" }}"
          volumeMounts:
            - name: script
              mountPath: /scripts/capture-deployment-completion.sh
              subPath: capture-deployment-completion.sh
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 256Mi
      volumes:
        - name: script
          configMap:
            name: helm-telemetry-completion-script
            defaultMode: 0755
{{- end }}
