{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "anysource.fullname" . }}-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "anysource.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.awsCertificate.enabled }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.awsCertificate.arn }}
    {{- end }}
    {{- if eq .Values.ingress.className "alb" }}
    # ALB-specific health check configurations
    alb.ingress.kubernetes.io/healthcheck-path: /api/v1/utils/health-check/
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "10"
    alb.ingress.kubernetes.io/healthy-threshold-count: "2"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    # Backend target group attributes
    alb.ingress.kubernetes.io/target-group-attributes: |
      stickiness.enabled=false,
      deregistration_delay.timeout_seconds=30,
      stickiness.type=lb_cookie,
      stickiness.lb_cookie.duration_seconds=86400
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and .Values.ingress.tls.enabled (not .Values.awsCertificate.enabled) }}
  tls:
    - hosts:
        - {{ .Values.global.domain }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.service.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.service.frontend.port }}
{{- end }}
